; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F405RG]
platform = ststm32
board = genericSTM32F405RG
framework = arduino
monitor_speed = 230400
upload_protocol = dfu
lib_archive = false
lib_deps =
    askuric/Simple FOC
    ;simplefoc/SimpleFOCDrivers
    ;simplefoc/SimpleCANio
    https://github.com/simplefoc/Arduino-FOC-drivers.git#dev
    https://github.com/simplefoc/SimpleCANio.git  
build_flags = 
    -D HSE_VALUE=8000000
	-D USBCON
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBD_USE_CDC
    -D HAL_CAN_MODULE_ENABLED
    ; -D CAN_DEBUG ; SimpleCANio debug flag, comment out to disable debug prints
